-- HYPRLAND v0.55+ NATIVE LUA CONFIG
-- #######################################################################################

local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "~/.config/rofi/launchers/type-6/launcher.sh"
local powerMenu = "~/.config/rofi/powermenu/type-5/powermenu.sh"
local screenshotMenu = "~/.config/rofi/applets/bin/screenshot.sh"

-- 1. Lokale machine.lua laden
local has_machine, machine = pcall(require, "machine")
if not has_machine then
	machine = {}
end
--

if machine.binds then
	for _, b in ipairs(machine.binds) do
		local key_combo = b[1]

		-- Falls KEIN " + " im String existiert (z.B. reine Medientasten wie XF86...),
		-- hängen wir ein leeres Präfix an, damit die v0.55+ API die Taste sauber parst.
		if not key_combo:find("%+") then
			key_combo = " + " .. key_combo
		end

		hl.bind(key_combo, hl.dsp.exec_cmd(b[2]), { repeating = b.repeating })
	end
end

--2. Declarative Config (Settings, Rules, Looks)
hl.config({
	autogenerated = false,

	-- Monitore aus der machine.lua laden
	monitor = machine.monitors or { { ",", "preferred", "auto", 1 } },

	env = {
		{ "XCURSOR_SIZE", "24" },
		{ "HYPRCURSOR_SIZE", "24" },
		{ "QT_QPA_PLATFORMTHEME", "qt6ct" },
	},

	general = {
		gaps_in = 5,
		gaps_out = 20,
		border_size = 2,
		-- Sichere 8-Zeichen rgba Hex-Codes für volle Deckkraft
		["col.active_border"] = "rgba(ff0000ff)",
		["col.inactive_border"] = "rgba(1a1a1aff)",
		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = { enabled = true, range = 4, render_power = 3, color = "rgba(1a1a1aff)" },
		blur = { enabled = true, size = 3, passes = 1, vibrancy = 0.1696 },
	},

	animations = {
		enabled = true,
		bezier = {
			{ "easeOutQuint", 0.23, 1, 0.32, 1 },
			{ "easeInOutCubic", 0.65, 0.05, 0.36, 1 },
			{ "linear", 0, 0, 1, 1 },
			{ "almostLinear", 0.5, 0.5, 0.75, 1 },
			{ "quick", 0.15, 0, 0.1, 1 },
		},
		animation = {
			{ "global", 1, 10, "default" },
			{ "border", 1, 5.39, "easeOutQuint" },
			{ "windows", 1, 4.79, "easeOutQuint" },
			{ "windowsIn", 1, 4.1, "easeOutQuint", "popin 87%" },
			{ "windowsOut", 1, 1.49, "linear", "popin 87%" },
			{ "fadeIn", 1, 1.73, "almostLinear" },
			{ "fadeOut", 1, 1.46, "almostLinear" },
			{ "fade", 1, 3.03, "quick" },
			{ "layers", 1, 3.81, "easeOutQuint" },
			{ "layersIn", 1, 4, "easeOutQuint", "fade" },
			{ "layersOut", 1, 1.5, "linear", "fade" },
			{ "fadeLayersIn", 1, 1.79, "almostLinear" },
			{ "fadeLayersOut", 1, 1.39, "almostLinear" },
			{ "workspaces", 1, 1.94, "almostLinear", "fade" },
			{ "workspacesIn", 1, 1.21, "almostLinear", "fade" },
			{ "workspacesOut", 1, 1.94, "almostLinear", "fade" },
			{ "zoomFactor", 1, 7, "quick" },
		},
	},

	dwindle = { preserve_split = true },
	master = { new_status = "master" },
	misc = { force_default_wallpaper = -1, disable_hyprland_logo = false, vrr = 1 },

	input = {
		kb_layout = "de",
		follow_mouse = 1,
		sensitivity = 0,
		touchpad = { natural_scroll = true },
	},
}) -- HIER ENDET hl.config()

-- #######################################################################################
-- 2.1 Gestures, Devices & Window Rules (Eigenständige Funktionen)
-- #######################################################################################

-- 3-Finger-Geste aktivieren
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Spezifische Geräteeinstellungen
hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })

-- Fensterregeln (windowrules)
hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
	no_focus = true,
})

hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },
	move = "20 monitor_h-120",
	float = true,
})

-- Umgebungsvariablen aus machine.lua mergen
if machine.env then
	for _, e in ipairs(machine.env) do
		hl.exec_cmd("hyprctl keyword env " .. e[1] .. "," .. e[2])
	end
end

-- 3. Autostart Hook
hl.on("hyprland.start", function()
	local cmds = {
		"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
		"systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
		"killall xdg-desktop-portal-hyprland; /usr/lib/xdg-desktop-portal-hyprland &",
		"killall xdg-desktop-portal; /usr/lib/xdg-desktop-portal &",
		"sleep 1 && waybar",
		"hyprctl setcursor Adwaita 24",
		"gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'",
		"~/.local/bin/trcc gui",
		"pipeweaver-daemon --background",
		"/home/raphaelk/automation/spotify.sh",
	}

	-- Globale Autostarts ausführen
	for _, cmd in ipairs(cmds) do
		hl.exec_cmd(cmd)
	end

	-- Gerätespezifische Autostarts aus der machine.lua ausführen
	if machine.autostart then
		for _, cmd in ipairs(machine.autostart) do
			hl.exec_cmd(cmd)
		end
	end
end)

-- 4. Keybinds (Echt Nativ)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen(1))
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("ALT + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(powerMenu))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(screenshotMenu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Headless Script
hl.bind(
	mainMod .. " + R",
	hl.dsp.exec_cmd(
		'bash -c "killall wayvnc; hyprctl keyword monitor HEADLESS-2,disable; hyprctl output create headless && sleep 1 && hyprctl keyword monitor HEADLESS-2,1920x1080@60,1920x0,1 && wayvnc --output HEADLESS-2 0.0.0.0 5900"'
	)
)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("killall wayvnc && hyprctl keyword monitor HEADLESS-1,disable"))

-- Fokus verschieben
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Workspaces
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Lautstärke & Helligkeit
hl.exec_cmd("hyprctl keyword bindel ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+")
hl.exec_cmd("hyprctl keyword bindel ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")
hl.exec_cmd("hyprctl keyword bindel ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
hl.exec_cmd("hyprctl keyword bindel ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")
hl.exec_cmd("hyprctl keyword bindel ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+")
hl.exec_cmd("hyprctl keyword bindel ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-")

-- Playerctl & Screenshot
hl.exec_cmd("hyprctl keyword bindl , XF86AudioNext, exec, playerctl next")
hl.exec_cmd("hyprctl keyword bindl , XF86AudioPause, exec, playerctl play-pause")
hl.exec_cmd("hyprctl keyword bindl , XF86AudioPlay, exec, playerctl play-pause")
hl.exec_cmd("hyprctl keyword bindl , XF86AudioPrev, exec, playerctl previous")
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
